In [201]:
import torch

 *`torch.eye()`* returns an identity tensor

In [202]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

*`torch.ones()`* returns a tensor with all element equal to 1

In [203]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

*`torch.zeros()`*` returns a tensor with all element equal to 0

In [204]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

*`torch.rand()`* returns a tensor with random elements

In [205]:
torch.rand(2, 3)

tensor([[0.8737, 0.7268, 0.0082],
        [0.6804, 0.7670, 0.1680]])

In [206]:
a = torch.rand(3, 3)

*`.shape`* and  *`.size()`* are used to get rank and axes of a tensor

In [207]:
a.shape

torch.Size([3, 3])

In [208]:
a.size()

torch.Size([3, 3])

In [209]:
a = torch.rand(3, 3)

You can reshape your tensor using *`.reshape()`* and *`.view()`* There will be no effect on elements of the tensor

In [210]:
b = a.reshape(1, 9)

In [211]:
b = a.view(1, 9)

In [212]:
print(b)

tensor([[0.6447, 0.6427, 0.0827, 0.0625, 0.5221, 0.2536, 0.3531, 0.2021, 0.9351]])


*`.numel()`* returns the total no of elements present inside the tensor

In [213]:
b.numel()

9

In [214]:
b = torch.rand(3, 3, 3)

In [215]:
print(b[0])

tensor([[0.3407, 0.3775, 0.5115],
        [0.3310, 0.7052, 0.3048],
        [0.7715, 0.8979, 0.8636]])


In [216]:
a = torch.ones(2, 3)

In [217]:
b = torch.zeros(3, 2)


*`torch.mm()`* is used for tensor multiplication

In [218]:
torch.mm(a, b)

tensor([[0., 0.],
        [0., 0.]])

use of *`.flatten()`*  and *`.squeeze()`*

In [219]:
a = torch.ones(3,3)

In [220]:
a.reshape(1, -1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [221]:
a.squeeze()

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [222]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])