In [2]:
import torch

In [10]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype = torch.float32)

In [11]:
t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype = torch.float32)

In [12]:
t1+t2

tensor([[10., 10.],
        [10., 10.]])

In [13]:
t1-t2

tensor([[-8., -6.],
        [-4., -2.]])

Here comes the concept of broadcasting, For element wise operations shape of the tensor should be same but for below operation the scalar value will be converted to a similar tensor using broadcasting

In [14]:
t1+2

tensor([[3., 4.],
        [5., 6.]])

In [15]:
t1/2


tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])