In [28]:
import torch

In [29]:
import  numpy as np

In [30]:
a = np.array([1, 2, 3])

In [31]:
type(a)

numpy.ndarray

In [32]:
print(a)

[1 2 3]


In [39]:
b = torch.tensor(a)

In [40]:
type(b)

torch.Tensor

In [41]:
print(b)

tensor([1, 2, 3], dtype=torch.int32)


In [42]:
c = b.numpy()

In [43]:
type(c)

numpy.ndarray

In [44]:
print(c)

[1 2 3]
